### ISSUE TITLE
rubocop-erb's default config is overwritten by .rubocop_todo.yml

### ISSUE THREAD

**Issue by Earlopain** [r7kamura/rubocop-erb#15]
I have a codebase which employs `.rubocop_todo.yml` to silence existing violations. Once I add this gem that file is partially ignored.
I can fix this if I add this to my `.rubocop.yml`:

```yml
inherit_mode:
  merge:
    - Exclude
```

Makes sense. Perhaps this should be added to the readme as a general recommendation? There would probably also be some sort of issue if I specify excludes for cops in my own rubocop config.

**Comment by r7kamura** [comment]
It is puzzling that this would be the case after adding this gem. Can you please tell me more about how I can reproduce it so I can try to reproduce it?

**Comment by Earlopain** [comment]
Of course, I can try to create a small reproduction case and link it here once I've got time.

**Comment by Earlopain** [comment]
I was misinterpreting what I was looking at. The file is not being ignored, the default of this gem is overwritten.

If a cop is exluded as part of `.rubocop_todo.yml` which also is also being ignored in [config/default.yml](https://github.com/r7kamura/rubocop-erb/blob/afbaafb02b3e189aeecde7cb027c88419f4d99fb/config/default.yml) then those cops will run on erb files.

Heres a small example:

.rubocop_todo.yml
```yml
# This configuration was generated by
# `rubocop --auto-gen-config --auto-gen-only-exclude --exclude-limit 20000`
# on 2023-02-23 22:33:45 UTC using RuboCop version 1.46.0.
# The point is for the user to remove these configuration records
# one by one as the offenses are removed from the code base.
# Note that changes in the inspected code, or installation of new
# versions of RuboCop, may require this file to be generated again.

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: final_newline, final_blank_line
Layout/TrailingEmptyLines:
  Exclude:
    - 'test.rb' # This file isn't needed, just the 'Exlude' entry
```
.rubocop.yml
```yml
inherit_from: .rubocop_todo.yml

require:
  - rubocop-erb

AllCops:
  NewCops: enable
```

test.html.erb
```erb
<% method_call_with_parens() %>
```
-----
Running rubocop produces this output:
```
Offenses:

test.html.erb:1:27: C: [Correctable] Style/MethodCallWithoutArgsParentheses: Do not use parentheses for method calls with no arguments.
<% method_call_with_parens() %>
                          ^^
test.html.erb:1:30: C: [Correctable] Layout/TrailingEmptyLines: Final newline missing.
<% method_call_with_parens() %>
```

The second offence goes away once you add this to the rubocop config:
```yml
inherit_mode:
  merge:
    - Exclude
```
